### ISSUE TITLE
Android back button going back

### ISSUE THREAD

**Issue by deadendpl** [lydavid/MusicSearch#1153]
Android back button exits the app.
It could act as the back button on the upper left on the screen.

https://github.com/user-attachments/assets/d6a470a2-ed02-4eb5-b370-d8acfe2e23b6

**Comment by lydavid** [comment]
What's your phone manufacturer and android version?

**Comment by deadendpl** [comment]
I have Android 12.
My phone manufacturer is TCL.
![Screenshot_2024-10-06-16-17-13-540.jpg](https://github.com/user-attachments/assets/7921fa5e-61d4-4640-ae0f-8e9e85dbf66d)

**Comment by lydavid** [comment]
I can't seem to repro this on an Android 12 (though it's an emulator).

Is this happening consistently? 

And when you reopen the app, is it on the same screen? If it reopens in the search screen instead, then it may have crashed.

**Comment by lydavid** [comment]
Actually, I'm able to repro now. I missed the tap indicator in your video.
