### ISSUE TITLE
App crashes after hiding tracks in a medium

### ISSUE THREAD

**Issue by deadendpl** [lydavid/MusicSearch#1209]
In the video, it happened after hiding 6th medium in [this release](https://musicbrainz.org/release/f7a96d7b-67a7-4bc6-89dc-2a426f51b1f0). That medium has 338 tracks.

https://github.com/user-attachments/assets/a77e81aa-c1ee-4b06-b050-068e57d4134a

**Comment by lydavid** [comment]
I tried it across a few devices (including physical ones) and can't seem to reproduce this. Could your device be low on memory when this happened?

Here are some emulator runs between API 26-35: https://github.com/lydavid/MusicSearch/actions/runs/11654629281?pr=1212

**Comment by deadendpl** [comment]
I tried it again. Out of 3 GB of memory, 1,6 was used. The app still crashed.

**Comment by deadendpl** [comment]
I found out another bug.
After scrolling through that bug medium, the whole medium list appears again.
![Screenshot_2024-11-06-11-33-06-731.jpg](https://github.com/user-attachments/assets/65c04118-9111-4ae8-b7e0-36c773a48611)

**Comment by deadendpl** [comment]
I cleared the app's data, and now it works.

I realized that the first 6 mediums had artist credits before the release got track list edits, and the next 6 had artist creits after those edits.
Now there are 6 mediums as it should be, and the app didn't crash after collapsing the 6th medium.

**Comment by lydavid** [comment]
Thanks for looking into it further.

I'll close this issue but if you find this to be a common problem that comes up when editing, please open another issue for it. If you do encounter this again, I'm curious whether swiping down to refresh will resolve this instead of having to wipe the app's data.
