### ISSUE TITLE
Collapsing of a medium crashes app (again)

### ISSUE THREAD

**Issue by deadendpl** [lydavid/MusicSearch#1248]
Reupload of issue #1209, because I experienced it again.
Collapsing a medium on a release which had its track list edited crashes the app.
On the video I swipe down to refresh the track list, but the app still crashes.
The weird thing is the tracks with new artist are added to the bottom of (probably) original track list.

https://github.com/user-attachments/assets/930ffdee-a448-46ed-9418-95994c5d5322

**Comment by deadendpl** [comment]
In 1.9.0-beta3 it's fixed now.

**Comment by lydavid** [comment]
Thanks for confirming!
