### ISSUE TITLE
Learn MVI

### ISSUE THREAD

**Issue by lydavid** [lydavid/MusicSearch#583]
https://github.com/topics/mvi?l=kotlin

Choose one of:
- https://github.com/slackhq/circuit
- https://github.com/arkivanov/MVIKotlin
  - https://github.com/arkivanov/Decompose

Some other choices: https://github.com/terrakok/kmp-awesome#-architecture

**Comment by arkivanov** [comment]
For MVIKotlin please refer to https://github.com/arkivanov/MVIKotlin
😀

**Comment by lydavid** [comment]
Thanks! I'll try it out
