### ISSUE TITLE
mac-aarch64 app crashes when run with double click; windows app crashes when installed with .exe

### ISSUE THREAD

**Issue by lydavid** [lydavid/MusicSearch#974]
<img width="372" alt="Screenshot 2024-06-29 at 2 49 33 PM" src="https://github.com/lydavid/MusicSearch/assets/22302001/30505ee9-2fd4-4f1e-bf0e-c0ae053a799c">
<img width="963" alt="Screenshot 2024-06-29 at 2 49 46 PM" src="https://github.com/lydavid/MusicSearch/assets/22302001/305f1b00-4bf4-43a5-bf3a-53ce102c53f4">

**Comment by lydavid** [comment]
A workaround is to control click, `Show Package Contents` -> `Contents` -> `MacOS` -> double click `MusicSearch`.

**Comment by lydavid** [comment]
Try without `@ComponentScan`

**Comment by lydavid** [comment]
Crashes for Windows too when run through .exe installer from https://lydavid.github.io/MusicSearch/download.html

**Comment by lydavid** [comment]
I've tried commenting out that class and all of its usages. The error would change to another class from :shared:domain.

**Comment by lydavid** [comment]
Adding `implementation(projects.shared.domain)` to :desktop:app didn't fix it

**Comment by lydavid** [comment]
- [ ] build desktop app without koin

**Comment by lydavid** [comment]
Why does Koin work when run with https://github.com/lydavid/MusicSearch/issues/974#issuecomment-2198300274 but not double clicking?

**Comment by lydavid** [comment]
Related to https://github.com/InsertKoinIO/koin/issues/1639?

**Comment by lydavid** [comment]
Changing `"jdbc:sqlite:music_search.db"` to `JdbcSqliteDriver.IN_MEMORY` resolves the crash.
But we want to persist our database.

**Comment by lydavid** [comment]
Existing issue: https://youtrack.jetbrains.com/issue/CMP-5341

**Comment by artalejo** [comment]
Hello there @lydavid , did you find a work around still using the persist database? Or you can just not distribute the app because of this? I am facing the same issue.

**Comment by lydavid** [comment]
No, I have not been able to distribute with a persisting database. When I temporarily removed Koin for my desktop app to debug this, it worked because I removed SQLDelight.

**Comment by artalejo** [comment]
Right! I did find a solution, please check what they suggested in this Slack thread. Basically you need to set the path of the database depending on the jvm platform that you are distributing so that the operative system does find it.

https://kotlinlang.slack.com/archives/C01D6HTPATV/p1725877136015339

I have used  https://github.com/psuzn/multiplatform-paths library to find the cache path independent on the platform and then proceed to use it in the sqldelight driver. 

```
actual class GameDetailsDatabaseDriver {
    actual fun createDriver(): SqlDriver {
        val appCacheDirectory = appCacheDirectory(appId = jvmPackageName, createDir = true)
       ---> This is the important part, using the cache directory path in the jdbc:sqlite.
        return JdbcSqliteDriver(
            url = "jdbc:sqlite:$appCacheDirectory/gameDetails.db", 
            schema = GameDetailsDatabase.Schema
        )
    }
}
```

Let me know if it helps.

**Comment by lydavid** [comment]
Hey, thanks for this detailed response! Sorry, I didn't see this sooner. I've tried your solution locally and it worked perfectly.

I'll test the deploy tomorrow and report back.

**Comment by lydavid** [comment]
I've verified it on Mac and Windows. Thanks again!
